# Generated by Django 5.2.1 on 2025-06-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticles',
            fields=[
                ('news_id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('original_content', models.TextField()),
                ('source_url', models.TextField()),
                ('source_name', models.CharField(max_length=100)),
                ('publish_date', models.DateTimeField()),
                ('crawl_date', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('translated_content', models.TextField(blank=True, null=True)),
                ('translation_status', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_articles',
                'managed': False,
            },
        ),
    ]
