# Generated by Django 5.2.1 on 2025-11-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cn_title', models.TextField()),
                ('original_content', models.TextField()),
                ('source_url', models.TextField()),
                ('source_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publish_date', models.DateTimeField()),
                ('crawl_date', models.DateTimeField(blank=True, null=True)),
                ('result', models.TextField()),
                ('translated_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('translator', models.CharField(blank=True, max_length=50, null=True)),
                ('analyzer', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'news_articles',
                'managed': False,
            },
        ),
    ]
